name: Commit comment or pull request comment triggered build

on:
  push:
    branches: 
      - 'release/**'
  issue_comment:
    types:
      - created

jobs:
  check_enabled_trigger_event:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    outputs:
      target_branch_name: ${{ steps.target_branch_name.outputs.branch_name }}
      target_commit_hash: ${{ steps.target_branch_name.outputs.commit_hash }}

    steps:
      - name: Get triggered event
        id: trigger_event
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            if "${{ contains(github.event.head_commit.message, '[build]') }}"; then
              echo "::set-output name=name::pushed_branch"
            fi
          elif [ "${{ github.event_name }}" = "issue_comment" ] && [ "${{ toJson(github.event.issue.pull_request) }}" != "null" ]; then
            if "${{ contains(github.event.comment.body, '[build]') }}"; then
              echo "::set-output name=name::posted_pull_request_comment"
            fi
          fi

      - name: Get comapre branch when posted pull request comment
        if: steps.trigger_event.outputs.name == 'posted_pull_request_comment'
        uses: actions/github-script@v3
        id: compare_branch
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head

      - name: Get target branch when pushed branch
        id: pushed_branch
        if: steps.trigger_event.outputs.name == 'pushed_branch'
        run: |
          echo "::set-output name=branch_name::${{ github.event.ref }}"
          echo "::set-output name=commit_hash::${{ github.event.sha }}"

      - name: Get target branch when posted pull request comment
        id: posted_pull_request
        if: steps.trigger_event.outputs.name == 'posted_pull_request_comment'
        run: |
          echo "::set-output name=branch_name::refs/heads/${{ fromJson(steps.compare_branch.outputs.result).ref }}"
          echo "::set-output name=commit_hash::${{ fromJson(steps.compare_branch.outputs.result).sha }}"

      - name: Set target branch
        id: target_branch_name
        run: |
          if [ "${{ steps.trigger_event.outputs.name }}" == "posted_pull_request_comment" ]; then
            echo "::set-output name=branch_name::${{ steps.posted_pull_request.outputs.branch_name }}"
            echo "::set-output name=commit_hash::${{ steps.posted_pull_request.outputs.commit_hash }}"
          elif [ "${{ steps.trigger_event.outputs.name }}" == "pushed_branch" ]; then
            echo "::set-output name=branch_name::${{ steps.pushed_branch.outputs.branch_name }}"
            echo "::set-output name=commit_hash::${{ steps.pushed_branch.outputs.commit_hash }}"
          fi

  build:
    needs: check_enabled_trigger_event
    if: needs.check_enabled_trigger_event.outputs.target_branch_name != ''
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Dump
        run: |
          echo "${{ needs.check_enabled_trigger_event.outputs.target_branch_name }}"
          echo "${{ needs.check_enabled_trigger_event.outputs.target_commit_hash }}"
