name: Commit or pull request comment triggered build

on:
  push:
    branches: 
      - 'release/**'
  issue_comment:
    types:
      - created

jobs:
  check_triggered_comment:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: github actions execution info
        run: echo "${{ toJson(github) }}"

      - name: Extract trigger string from commit comment
        if: github.event_name == 'push'
        run: echo "pushed."
    
      - name: Extract trigger string from pull request review comment
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null
        run: echo "issue comment created."
  
