name: Pull request merged build

on:
  pull_request:
    branches:
      - build
      - master
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    defaults:
      run:
        shell: bash

    steps:
      - name: github actions execution info
        run: |
          echo "${{ toJson(github) }}"

      - name: get pull request info
        id: pull_request_info
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data

      - name: pull request info
        run: |
          echo "${{ steps.pull_request_info.outputs.result }}"
