name: Pull request merged build

on:
  pull_request:
    branches:
      - build
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    defaults:
      run:
        shell: bash

    steps:
      - name: github actions execution info
        run: |
          echo "${{ toJson(github) }}"
